---
title: "Git_00"
author: "Netalia Ventura"
date: "Year 2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

"When midnight mists are creeping,
And all the land is sleeping,
Around me tread the mighty dead,
And slowly pass away.
Lo, warriors, saints, and sages,
From out the vanished ages,
With solemn pace and reverend face
Appear and pass away."

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

"Whose woods these are I think I know.   
His house is in the village though;   
He will not see me stopping here   
To watch his woods fill up with snow.   
My little horse must think it queer   
To stop without a farmhouse near   
Between the woods and frozen lake   
The darkest evening of the year."

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,
      Shining with all his might:
He did his very best to make
      The billows smooth and bright —
And this was odd, because it was
      The middle of the night."

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

"I'll tell you how the sun rose, -
A ribbon at a time.
The steeples swam in amethyst,
The news like squirrels ran.
The hills untied their bonnets,
The bobolinks begun.
Then I said softly to myself,
“That must have been the sun!”

But how he set, I know not.
There seemed a purple stile
Which little yellow boys and girls
Were climbing all the while

Till when they reached the other side,
A dominie in gray
Put gently up the evening bars,
And led the flock away."
- EMILY DICKINSON
